import { chromium } from "playwright";
import { childLogger } from "../../logger.js";

const log = childLogger("pdfEngine");

export interface PdfOptions {
  headerTitle?: string;
  footerText?: string;
}

/** Renders report HTML to a PDF buffer via a headless Chromium instance
 * (Playwright), with institutional header/footer, page numbers, and A4
 * layout. No AI tokens are used in this path — it is pure HTML->PDF. */
export async function renderHtmlToPdf(html: string, options: PdfOptions = {}): Promise<Buffer> {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle" });

    const headerTemplate = `
      <div style="font-size:9px; width:100%; padding:0 24px; color:#8a8fa3; display:flex; justify-content:space-between;">
        <span>${options.headerTitle ?? "INDUSS Research Intelligence"}</span>
      </div>`;
    const footerTemplate = `
      <div style="font-size:9px; width:100%; padding:0 24px; color:#8a8fa3; display:flex; justify-content:space-between;">
        <span>${options.footerText ?? "Confidential — Generated by INDUSS MCP"}</span>
        <span><span class="pageNumber"></span> / <span class="totalPages"></span></span>
      </div>`;

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate,
      footerTemplate,
      margin: { top: "60px", bottom: "50px", left: "24px", right: "24px" },
    });

    return Buffer.from(pdfBuffer);
  } catch (err) {
    log.error({ err }, "PDF rendering failed");
    throw err;
  } finally {
    await browser.close();
  }
}
